BUCKET: biomass-earthdata-dashboard
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
- NCEO_Africa.json
- CCI_BIOMASS.json
- GEDI_L4B.json
- ICESat-2_boreal.json
- NASA_JPL_mystery.json
SITES:
- japan
- paraguay
- peru
- wales
