BUCKET: biomass-earthdata-dashboard
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
  - nceo_africa
  - nceo_africa_sd
  - cci_biomass
  - cci_biomass_sd
  - gedi_l4b
  - gedi_l4b_se
  - nasa_jpl
  - nasa_jpl_se
  - paraguay_forest_mask
  - paraguay_tree_cover
  - paraguay_estimated_biomass
  - icesat2_boreal_biomass
  - icesat2_boreal_biomass_se
  - icesat2_boreal_landsat8
  - icesat2_boreal_topo
  - gedi_calval_plots
COUNTRY_PILOTS:
  - japan
  - paraguay
  - peru
  - solomon_islands
  - wales
PRODUCTS:
  - global
  - cci_biomass
  - gedi_l4b
  - icesat2_boreal
  - nasa_jpl
  - nceo_africa
