BUCKET: biomass-earthdata-dashboard-aimee
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
- NCEO_Africa.json
- NCEO_Africa_SD.json
- CCI_BIOMASS.json
- GEDI_L4B.json
- ICESat-2_boreal.json
- nasa-jpl.json
- paraguay-forest-mask.json
- paraguay-tree-cover.json
- paraguay-estimated-biomass.json
- gedi-calval-plots.json
COUNTRY_PILOTS:
- japan
- paraguay
- peru
- wales
PRODUCTS:
- NCEO_Africa
- CCI_BIOMASS
- GEDI_L4B
- ICESat-2_boreal
- NASA_JPL
