BUCKET: biomass-earthdata-dashboard
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
- NCEO_Africa.json
- NCEO_Africa_SD.json
- CCI_BIOMASS.json
- GEDI_L4B.json
- nasa-jpl.json
- paraguay-forest-mask.json
- paraguay-tree-cover.json
- paraguay-estimated-biomass.json
- ABoVE_biomass.json
- ABoVE_biomass_se.json
- ABoVE_landsat8.json
- ABoVE_topo.json
- gedi-calval-plots.json
COUNTRY_PILOTS:
- japan
- paraguay
- peru
- wales
PRODUCTS:
- all
- ABoVE_Boreal
- CCI_BIOMASS
- GEDI_L4B
- NASA_JPL
- NCEO_Africa
